CREATE OR REPLACE FUNCTION capture_start() RETURNS boolean
AS 'MODULE_PATHNAME', 'sql_capture_start'
LANGUAGE C STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION capture_stop() RETURNS boolean
AS 'MODULE_PATHNAME', 'sql_capture_stop'
LANGUAGE C STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION capture_reset() RETURNS boolean
AS 'MODULE_PATHNAME', 'sql_capture_reset'
LANGUAGE C STRICT PARALLEL SAFE;
