[package]
name = "pgr"
version = "0.2.0"
edition = "2024"

[workspace]
members = [
    ".",
    "capture-ebpf",
    "capture-common",
]

[dependencies]
aya = "0.14.0"
capture-common = { path = "capture-common", features = ["user"] }
bytes = "1.12.1"
clap = { version = "4.6.4", features = ["derive"] }
etherparse = "0.21.0"
md5 = "0.8.1"
pcap-parser = "0.17.0"
time = { version = "0.3.54", features = ["formatting", "macros", "local-offset"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "time"] }
zstd = {version = "0.13.3", features = ["zstdmt"] }
libc = "0.2.189"
crossbeam-channel = "0.5.16"
anyhow = "1.0.104"
bytesize = "2.7.0"
aya-log = "0.3.0"
humantime = "2.4.0"
quanta = "0.12.6"
mio = { version = "1.2.2", features = ["net", "os-poll"] }
ctrlc = "3.5.2"
io-uring = "0.7.13"
socket2 = "0.6.5"

[build-dependencies]
cargo_metadata = "0.23.1"
aya-build = { git = "https://github.com/aya-rs/aya" }
anyhow = "1.0.104"

[profile.release]
debug = true
